language: java
env:
  - VERIFY_USE_PUBLIC_BINARIES=true
jdk:
  - openjdk8
  - openjdk11
services:
  - docker
before_script:
  - echo "before script" #docker build -f PublicDockerfile -t verify-event-emitter .
script:
  - ./gradlew clean build integrationTest
addons:
  apt:
    packages:
      - python3
      - python3-pip
